name: Infrastructure and Frontend CI/CD

on:
  schedule:
    - cron: '*/3 * * * *'

jobs:
  drift-check:
    name: Checkout Terraform Plan and Apply if Drift Detected
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform validate
        run: terraform validate

      - name: Switch to dev workspace
        run: |
          terraform workspace select -or-create dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform plan
        id: plan
        run: |
          PLAN_OUTPUT=$(terraform plan)
          echo "$PLAN_OUTPUT"  # Output plan for reference
          if [[ $(echo "$PLAN_OUTPUT" | grep -c "No changes") -eq 0 ]]; then
            echo "::set-output name=drift-detected::true"
          else
            echo "::set-output name=drift-detected::false"
          fi

      - name: Terraform apply
        if: steps.plan.outputs.drift-detected == 'true'
        run: |
          retries=5
          until terraform apply --auto-approve || [ $retries -eq 0 ]
          do
            sleep 10
            retries=$((retries-1))
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

